using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace WildPath.SourceGenerator;

internal static class InterceptorSourceEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<PathCallCandidate> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
        {
            return;
        }

        var source = new StringBuilder();
        AppendHeader(source);

        var pathFields = new Dictionary<string, string>(StringComparer.Ordinal);
        for (var index = 0; index < candidates.Length; index++)
        {
            var candidate = candidates[index];
            var key = candidate.RawPath + "\u001F" + candidate.SegmentsSource;
            if (pathFields.ContainsKey(key))
            {
                continue;
            }

            var fieldName = "__path" + pathFields.Count.ToString();
            pathFields.Add(key, fieldName);
            source.Append("    private static readonly global::WildPath.PathExpression ")
                .Append(fieldName)
                .AppendLine(" =");
            source.Append("        global::WildPath.PathExpression.Create(")
                .Append(SymbolDisplay.FormatLiteral(candidate.RawPath, true))
                .Append(", ")
                .Append(candidate.SegmentsSource)
                .AppendLine(");");
            source.AppendLine();
        }

        for (var index = 0; index < candidates.Length; index++)
        {
            AppendInterceptor(source, candidates[index], index, pathFields);
        }

        source.AppendLine("}");
        source.AppendLine("}");
        context.AddSource("WildPathInterceptors.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendHeader(StringBuilder source)
    {
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace System.Runtime.CompilerServices");
        source.AppendLine("{");
        source.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        source.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        source.AppendLine("        {");
        source.AppendLine("            _ = version;");
        source.AppendLine("            _ = data;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("namespace WildPath.Generated");
        source.AppendLine("{");
        source.AppendLine("static file class WildPathInterceptors");
        source.AppendLine("{");
    }

    private static void AppendInterceptor(
        StringBuilder source,
        PathCallCandidate candidate,
        int index,
        Dictionary<string, string> pathFields)
    {
        var key = candidate.RawPath + "\u001F" + candidate.SegmentsSource;
        var fieldName = pathFields[key];
        var returnType = candidate.MethodName == "Resolve"
            ? "string"
            : "global::System.Collections.Generic.IEnumerable<string>";

        source.Append("    [global::System.Runtime.CompilerServices.InterceptsLocation(")
            .Append(candidate.InterceptVersion.ToString())
            .Append(", ")
            .Append(SymbolDisplay.FormatLiteral(candidate.InterceptData, true))
            .Append(")] // ")
            .AppendLine(candidate.DisplayLocation);

        AppendSignature(source, candidate, index, returnType);
        source.Append("        => ");
        if (candidate.CallKind == CallKind.Static)
        {
            source.Append("global::WildPath.PathResolver.");
        }
        else
        {
            source.Append("global::WildPath.PathResolverExtensions.");
        }

        source.Append(candidate.MethodName)
            .Append('(');

        if (candidate.CallKind == CallKind.Extension)
        {
            source.Append("resolver, ");
        }

        source.Append(fieldName)
            .AppendLine(", token);");
        source.AppendLine();
    }

    private static void AppendSignature(
        StringBuilder source,
        PathCallCandidate candidate,
        int index,
        string returnType)
    {
        source.Append("    public static ")
            .Append(returnType)
            .Append(" __")
            .Append(candidate.MethodName)
            .Append(index.ToString())
            .Append('(');

        if (candidate.CallKind == CallKind.Extension)
        {
            source.Append("this global::WildPath.PathResolver resolver, ");
        }

        source.Append("string expression, global::System.Threading.CancellationToken token = default)");
        source.AppendLine();
    }
}
